project:
  type: website
  output-dir: docs

website:
  title: "Nombre de tu sitio"
  site-url: https://tu-usuario.github.io/nombre-del-repo/
  navbar:
    left:
      - text: Home
        href: index.qmd