project:
  type: website
  output-dir: "_site"

website:
  title: "SheInventor"
  site-url: https://paovazbar.github.io/paovazbar/
  navbar:
    left:
      - text: Home
        href: index.qmd
    right:
      - text: "Español"
        href: es/index.qmd
      - text: "English"
        href: en/index.qmd
      - text: "Français"
        menu:
        - text: "Introduction"
          href: fr/index.qmd
        - text: "Tutoriels"
          href: fr/tutoriels/tutorial1.qmd
        - text: "Bandes desinées"
          href: fr\comics\index.qmd

css: css/styles.css